apiVersion: batch/v1
kind: Job
metadata:
  name: ge-config-sync
  namespace: ge-dev
spec:
  template:
    spec:
      containers:
      - name: git-sync
        image: alpine/git:latest
        command:
        - /bin/sh
        - -c
        - |
          set -e
          # 1. Install dependencies
          apk add --no-cache git rsync openssh-client

          # 2. Setup SSH Key
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

          # 3. Clone the repo
          echo "Cloning repository..."
          git clone --depth 1 git@github.com:Rajp1011/PFHBE-Internal.git /tmp/build-repo

          # 4. Prepare Audit Log
          AUDIT_LOG="/mnt/pvc/GEService/sync_audit.log"
          TIMESTAMP=$(date -u "+%Y-%m-%d %H:%M:%S UTC")

          mkdir -p /mnt/pvc/GEService/Internal

          echo "-------------------------------------------" >> $AUDIT_LOG
          echo "Sync Started: $TIMESTAMP" >> $AUDIT_LOG

          # 5. Smart Sync
          echo "Starting sync for GEService..."
          rsync -avi --delete /tmp/build-repo/Internal/ /mnt/pvc/GEService/Internal/ > /tmp/changes.txt

          # 6. Format Audit Log
          grep -E '>f|\*deleting' /tmp/changes.txt | sed \
            -e 's/>f+++++++/[ ADDED   ]/g' \
            -e 's/>f.st....../[ UPDATED ]/g' \
            -e 's/\*deleting  /[ DELETED ]/g' >> $AUDIT_LOG

          echo "Sync Finished Successfully" >> $AUDIT_LOG
          echo "Sync Complete!"
        env:
        - name: SSH_KEY
          valueFrom:
            secretKeyRef:
              name: internal-raj-deploy-key
              key: ssh-privatekey
        volumeMounts:
        - name: storage
          mountPath: /mnt/pvc
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: ge-pvc
      restartPolicy: Never
  backoffLimit: 2