apiVersion: v1
kind: PersistentVolume
metadata:
  name: ge-pv-qa
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=0
    - gid=0
    - mfsymlinks
    - nobrl
  csi:
    driver: file.csi.azure.com
    volumeHandle: iGaming#gepvc777qa#ge-fileshare-qa
    volumeAttributes:
      shareName: ge-fileshare-qa
    nodeStageSecretRef:
      name: azure-storage-account-secret
      namespace: ge-qa
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ge-pvc-qa
  namespace: ge-qa
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: ge-pv-qa

