apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ge-service-1-qa-hpa
  namespace: ge-qa
  labels:
    app: ge-service
    shard: "1"
    env: qa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ge-service-1-qa
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ge-service-2-qa-hpa
  namespace: ge-qa
  labels:
    app: ge-service
    shard: "2"
    env: qa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ge-service-2-qa
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ge-service-3-qa-hpa
  namespace: ge-qa
  labels:
    app: ge-service
    shard: "3"
    env: qa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ge-service-3-qa
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ge-service-4-qa-hpa
  namespace: ge-qa
  labels:
    app: ge-service
    shard: "4"
    env: qa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ge-service-4-qa
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ge-service-5-qa-hpa
  namespace: ge-qa
  labels:
    app: ge-service
    shard: "5"
    env: qa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ge-service-5-qa
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70